

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#  splunk:
#    image: splunk/splunk:latest
#    container_name: splunk
#    environment:
#      SPLUNK_START_ARGS: --accept-license
#      SPLUNK_PASSWORD: changeme
#    ports:
#      - "8000:8000"  # Splunk UI
#      - "8088:8088"  # HEC port
#    volumes:
#      - splunk_data:/opt/splunk
  app:
    build: .
    container_name: article_app-backend
    restart: always
    depends_on:
      - mysql
#      - splunk
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPLUNK_HEC_URL: http://localhost:8088
      SPLUNK_HEC_TOKEN: 04a0b118-ea27-4e88-a268-16ae5447baee
      SPLUNK_HEC_ENABLE: true
    ports:
      - "8080:8080"
#  jenkins:
#    image: jenkins/jenkins:lts
#    restart: always
#    ports:
#      - "8083:8080"
#      - "50000:50000"
#    volumes:
#      - jenkins_home:/var/jenkins_home

volumes:
  mysql_data:
  jenkins_home:
#  splunk_data: